### ISSUE TITLE
bug found in test_remove_nth

### ISSUE THREAD

**Issue by alegrub88** [TUW-GEO-python-intro/Exercise-1#23]
https://github.com/TUW-GEO-python-intro/Exercise-1/blob/master/tests/test_functions.py#L95

the list l should be re-initialized before #L95 is execeuted

**Comment by cpaulik** [comment]
The function should not change the original list. Probably the instructions should be clearer on that.

**Comment by alegrub88** [comment]
Alright, I changed "remove_nth" accordingly and commited it to the branch for which I sent the pull request... it passes the test now.
